In [1]:
import numpy as np

In [2]:
# setup arrays
a = np.array([[1, 0],[2, -4]])
b = np.array([[-1, 6],[0, 2]])

In [14]:
# Matrix addition
# To do this, just add the corresponding values position for position to create a new matrix.

new_matrix = np.array([np.zeros(len(a), dtype=int), np.zeros(len(a), dtype=int)])
for i in range(len(a)):
    for j in range(len(a[i])):
        x = a[i,j] + b[i,j]
        new_matrix[i,j] = x

print("manual result):")
print(new_matrix)


# verify above is correct
print("numpy result: ")
print(a + b)



manual result):
[[ 0  6]
 [ 2 -2]]
numpy result: 
[[ 0  6]
 [ 2 -2]]


In [17]:
# Matrix subtraction

new_matrix = np.array([np.zeros(len(a), dtype=int), np.zeros(len(a), dtype=int)])
for i in range(len(a)):
    for j in range(len(a[i])):
        x = a[i,j] - b[i,j]
        new_matrix[i,j] = x

print("manual result):")
print(new_matrix)


# verify above is correct
print("numpy result: ")
print(a - b)


manual result):
[[ 2 -6]
 [ 2 -6]]
numpy result: 
[[ 2 -6]
 [ 2 -6]]
