In [1]:
import numpy as np

In [2]:
# setup arrays
a = np.array([[1, 0],[2, -4]])
b = np.array([[-1, 6],[0, 2]])

In [3]:
# Matrix addition
# To do this, just add the corresponding values position for position to create a new matrix.
# Matrices must be same size/dimension

new_matrix = np.array([np.zeros(len(a), dtype=int), np.zeros(len(a), dtype=int)])
for i in range(len(a)):
    for j in range(len(a[i])):
        x = a[i,j] + b[i,j]
        new_matrix[i,j] = x

print("manual addition result):")
print(new_matrix)


# verify above is correct
print("numpy addition result: ")
print(a + b)


# Matrix subtraction

new_matrix = np.array([np.zeros(len(a), dtype=int), np.zeros(len(a), dtype=int)])
for i in range(len(a)):
    for j in range(len(a[i])):
        x = a[i,j] - b[i,j]
        new_matrix[i,j] = x

print("manual subtraction result):")
print(new_matrix)


# verify above is correct
print("numpy subtraction result: ")
print(a - b)




manual addition result):
[[ 0  6]
 [ 2 -2]]
numpy addition result: 
[[ 0  6]
 [ 2 -2]]
manual subtraction result):
[[ 2 -6]
 [ 2 -6]]
numpy subtraction result: 
[[ 2 -6]
 [ 2 -6]]


In [4]:
# Scalar multiplication or multiplying a matrix by a scalar. 
# To do this just multiply each item  in the matrixby the scalar. 
# For this example 2 is the scalar

c = np.array([[1, 2, 3],[0, 1, 1]])
d = np.array([[2, 4, 6], [0, 1, 1]])


# manual multiplication result
new_matrix = np.array([np.zeros(len(c[0]), dtype=int), np.zeros(len(c[1]), dtype=int)])
for i in range(len(c)):
    for j in range(len(c[i])):
        x = 2 * c[i, j]
        new_matrix[i,j] = x


# manual multiplication result
print("manual multiplication result")
print(new_matrix)
        
# numpy multiplication result
print("numpy multiplication result")
print(c * 2)

manual multiplication result
[[2 4 6]
 [0 2 2]]
numpy multiplication result
[[2 4 6]
 [0 2 2]]


In [24]:
# Multiplying 2 matrices by eachother
# Multiplying matrices uses the dot product.
# Unlike addition/subtraction the matrices dont have to be the same dimensions.
# However the number of columns of the first matrix must equal the number of rows of the second matrix
# Each items of the row is multiplied by its corresponding column value then added together.

e = np.array([
    [2, 3],
    [-1, 0]])

f = np.array([
    [0, 1],
    [0, -1]])


# Come back to this
# https://www.udemy.com/course/linear-algebra-course/learn/lecture/15117830#overview

            


# numpy multiplication result
# Notice that the .dot function has to be used to get the right answer.
# The false answer is using elemental multiplication
# print("false answer for matrix multipliation of e * f:")
print(e * f)

#The correct answer is using dot product
# print("correct answer for matrix multiplication of e * f:")
print(e.dot(f))


[[0 3]
 [0 0]]
[[ 0 -1]
 [ 0 -1]]
