In [1]:
import numpy as np

In [2]:
# Create a regular python 2 dimensional array
L = [[1,2],[3,4]]

In [3]:
# Create a matrix or a 2 dimensional array
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [4]:
# Select the 2nd item of the first row just like how python works.
A[0][1]


2

In [5]:
# Select the 2nd item of the first row in the numpy way (python does not work like this)
A[0,1]

2

In [6]:
# Select a column
A[:,0]

array([1, 3])

In [7]:
# Get the transpose of the matrix
A.T

array([[1, 3],
       [2, 4]])

In [8]:
# Whats interesting about this is that numpy operate on the numpy array here same as the normal python array.
print(np.exp(A))
print(np.exp(L))

[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]
[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]


In [9]:
# To get the determinant of a matrix
np.linalg.det(A)

-2.0000000000000004

In [10]:
# To get inverse of a matrix
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [11]:
# How to get trace of matrix
np.trace(A)

5

In [12]:
# How to get diaganol elements of matrix
np.diag(A)

array([1, 4])

In [13]:
# How to get eigen values
np.linalg.eig(A)

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [ ]:
# How to see if