In [2]:
import numpy as np

In [ ]:
# Create a regular python 2 dimensional array
L = [[1,2],[3,4]]

In [3]:
# Create a matrix or a 2 dimensional array
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [4]:
# Select the 2nd item of the first row just like how python works.
A[0][1]


2

In [5]:
# Select the 2nd item of the first row in the numpy way (python does not work like this)
A[0,1]

2

In [6]:
# Select a column
A[:,0]

array([1, 3])

In [8]:
# Get the transpose of the matrix
A.T

array([[1, 3],
       [2, 4]])

In [11]:
# Whats interesting about this is that numpy operate on the numpy array here same as the normal python array.
print(np.exp(A))
print(np.exp(L))

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])