In [1]:
import numpy as np
L = [1, 2, 3]
A = np.array([1, 2, 3])

# Numpy exists to do Math. 


In [23]:
## Basics
# Create a matrix or a 2 dimensional array
A = np.array([[1,2],[3,4]])

# This is normal vector addition. Vectors (arrays) of the same size must be added otherwise error ocurrs
A = np.array([1,2, 3])
A + np.array([4,5,6])

# How to do vector multiplication
A = np.array([[1,2],[3,4]])
2 * A

# Squaring a vector
A = np.array([[1,2],[3,4]])
A**2

# How to do square root with numpy
print(np.sqrt(A))

#How to get logarithm of vector
print(np.log(A))

#How to calculate the exponential of an array. This is euler's number ~2.7
print(np.exp(A))


# How to get the dot product
np.dot(a, b)

# Another way way to get dot product
a @ b

#Working with numpy arrays
# Select the 2nd item of the first row just like how python works.
A = np.array([[1,2],[3,4]])
A[0][1]

# Select the 2nd item of the first row in the numpy way (python does not work like this)
A = np.array([[1,2],[3,4]])
A[0,1]

# Select a column
A = np.array([[1,2],[3,4]])
A[:,0]

# how to get the determinant of a matrix
np.linalg.det(A)

# To get inverse of a matrix
np.linalg.inv(A)

# How to get eigen values
np.linalg.eig(A)

[[1.         1.41421356]
 [1.73205081 2.        ]]
[[0.         0.69314718]
 [1.09861229 1.38629436]]
[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]


array([1, 3])

In [3]:

# This is broadcasting however not a normal linear algebra operation
A = np.array([[1,2],[3,4]])
A + [5]

array([[6, 7],
       [8, 9]])

In [8]:
# This is the manual way to calculate the dot product of 2 vectors
# zip function returns an iterator for both collections. If the size of each differs the smaller ones size gets used for both.

a = np.array([1,2])
b = np.array([3,4])

dot = 0

for e, f in zip(a, b):
    dot += e * f
dot

11

In [11]:
# How to calculate the magnitude or the scalar of a vector.
amag = np.sqrt((a*a).sum())

print("magnitude:")
print(amag)

# How to calculate the norm (same thing as magnitude)
norm = np.linalg.norm(a)

print("norm:")
print(norm)


magnitude:
2.23606797749979
norm:
2.23606797749979


In [12]:
# How to get the angle between 2 vectors
cosangle = np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))
print("cosangle:")
print(cosangle)

angle = np.arccos(cosangle)
print("angle in radians:")
print(angle)

cosangle:
0.9838699100999074
angle in radians:
0.17985349979247847


In [16]:
# Get the transpose of the matrix
A = np.array([[1,2],[3,4]])
A.T

array([[1, 3],
       [2, 4]])

In [19]:
# How to get trace of matrix
np.trace(A)

5

In [20]:
# How to get diaganol elements of matrix
A = np.array([[1,2],[3,4]])
np.diag(A)

array([1, 4])

In [21]:
# How to get eigen values
np.linalg.eig(A)

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [22]:
# How to see if