In [2]:
import numpy as np
L = [1, 2, 3]
A = np.array([1, 2, 3])

# Numpy exists to do Math. This shows how numpy arrays work.


In [11]:

# This is broadcasting however not a normal linear algebra operation
A + [5]

array([6, 7, 8])

In [13]:
# This is normal vector addition. Vectors (arrays) of the same size must be added otherwise error ocurrs
A + np.array([4,5,6])

array([5, 7, 9])

In [14]:
# This does vector multiplication
2 * A

array([2, 4, 6])

In [17]:
# Squaring a vector
A**2

array([1, 4, 9])

In [20]:
# Other operations with numpy
print(np.sqrt(A))
print(np.log(A))
print(np.exp(A))

[1.         1.41421356 1.73205081]
[0.         0.69314718 1.09861229]
[ 2.71828183  7.3890561  20.08553692]
